# This file can't work without its .env file

version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      network_mode:
      # ProtonVPN : In the case of ProtonVPN, it uses SERVER_COUNTRIES (and not SERVER_REGIONS)

    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}

    volumes:
      # filepath is anonymized, you can modify it
      - ${GLUETUN_CONFIG_DIR:-/srv/docker/gluetun}:/gluetun
    restart: unless-stopped
